shared:
  image: python:latest
  environment:
    FOO: bar
  annotations:
    screwdriver.cd/timeout: 5
jobs:
  lint:
    template: adamExampleNamespace/flake8_lint@latest
    annotations:
      # Run the job every day sometime between 4:00 am and 7:59 am UTC.
      screwdriver.cd/buildPeriodically: H H(4-7) * * *
  demo_env:
    requires: [ ~pr, ~commit ]
    environment:
      FOO: baz
      FIZZ: buzz
    steps:
      - display-env: echo "FOO = $FOO, FIZZ = $FIZZ"
      - init: pip install -r requirements.txt
      - lint: flake8 --benchmark main.py
  gen-token-1:
    requires: [ demo_env ]
    steps:
      - generate-token: python main.py | tee token.txt
      - store-token-metadata: meta set token1 "$(cat token.txt)"
      - save-token-artifact: mv token.txt $SD_ARTIFACTS_DIR
  gen-token-2:
    requires: [ demo_env ]
    steps:
      - generate-token: python main.py | tee token.txt
      - store-token-metadata: meta set token2 "$(cat token.txt)"
      - save-token-artifact: mv token.txt $SD_ARTIFACTS_DIR
  gen-token-3:
    requires: [ demo_env ]
    steps:
      - generate-token: python main.py | tee token.txt
      - store-token-metadata: meta set token3 "$(cat token.txt)"
      - save-token-artifact: mv token.txt $SD_ARTIFACTS_DIR
  morph-token-1:
    requires: [ gen-token-1 ]
    steps:
      - show-token: meta get token1
      - morph-token: meta set token1 "$(meta get token1 | tr '[:lower:]' '[:upper:]')"
  display:
    requires: [ morph-token-1, gen-token-2, gen-token-3 ]
    steps:
      - display-env: echo "FOO = $FOO, FIZZ = $FIZZ"
      - show-tokens: meta get token1; meta get token2; meta get token3
