shared:
  image: python:latest
  environment:
    FOO: bar
  annotations:
    screwdriver.cd/timeout: 5
jobs:
  test:
    requires: [ ~pr, ~commit ]
    environment:
      FOO: baz
      FIZZ: buzz
    annotations:
      # Run the job every day sometime between 4:00 am and 7:59 am UTC.
      screwdriver.cd/buildPeriodically: H H(4-7) * * *
    steps:
      - display-env: echo "FOO = $FOO, FIZZ = $FIZZ"
      - init: pip install -r requirements.txt
      - lint: flake8 --benchmark main.py
  gen-token-1:
    requires: [ test ]
    steps:
      - generate-token: python main.py | tee token.txt
      - store-token-metadata: meta set token1 "$(cat token.txt)"
      - save-token-artifact: mv token.txt $SD_ARTIFACTS_DIR
  gen-token-2:
    requires: [ test ]
    steps:
      - generate-token: python main.py | tee token.txt
      - store-token-metadata: meta set token2 "$(cat token.txt)"
      - save-token-artifact: mv token.txt $SD_ARTIFACTS_DIR
  gen-token-3:
    requires: [ test ]
    steps:
      - generate-token: python main.py | tee token.txt
      - store-token-metadata: meta set token3 "$(cat token.txt)"
      - save-token-artifact: mv token.txt $SD_ARTIFACTS_DIR
  display:
    requires: [ gen-token-1, gen-token-2, gen-token-3 ]
    steps:
      - display-env: echo "FOO = $FOO, FIZZ = $FIZZ"
      - show-token: meta get token
