shared:
  image: python:latest
  environment:
    FOO: bar
  annotations:
    screwdriver.cd/timeout: 5
jobs:
  generate:
    requires: [ ~pr, ~commit ]
    environment:
      FOO: baz
      FIZZ: buzz
    annotations:
      # Run the job every day sometime between 4:00 am and 7:59 am UTC.
      screwdriver.cd/buildPeriodically: H H(4-7) * * *
    steps:
      - display-env: echo "FOO = $FOO, FIZZ = $FIZZ"
      - init: pip install -r requirements.txt
      - lint: flake8 --benchmark main.py
      - generate-token: python main.py | tee token.txt
      - store-token-metadata: meta set token "$(cat token.txt)"
      - save-token-artifact: mv token.txt $SD_ARTIFACTS_DIR
  display:
    requires: [ generate ]
    steps:
      - display-env: echo "FOO = $FOO, FIZZ = $FIZZ"
      - show-token: meta get token
